#include <stdio.h>

main()
{
	printf("Nama: Zahratul laily \n");
	printf("NIM : F1B019146 \n");
	printf("Kelompok: 25 \n");
	
char* nim_ray[5]={"f1b019123","f1b019124","f1b019125","f1b019127","f1b019146",};
	printf("nimmahasiswake- 1 = %s\n",nim_ray[0]);
	printf("nimmahasiswake- 2 = %s\n",nim_ray[1]);
	printf("nimmahasiswake- 3 = %s\n",nim_ray[2]);
	printf("nimmahasiswake- 4 = %s\n",nim_ray[3]);
	printf("nimmahasiswake- 5 = %s\n",nim_ray[4]);
	printf("nimmahasiswake- 6 = %s\n",nim_ray[5]);
	
}


